name: node-docker-pm2-ssl

services:
  # NODE
  node-app:
    image: sen00/node-nginx-ssl:nodeapp
    restart: unless-stopped
    container_name: node-app
    user: "node"
    volumes:
      - node-app:/home/node/node-app
    environment:
      - NODE_ENV=production
      # DONT CHANGE PORT
      - PORT=3000
    networks:
      - main-network

  # NGINX
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: sen00/node-nginx-ssl:nginx-first
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_CONTAINER_NAME=node-app
      # Port of node is 3000
      - DOMAIN=senservers.com
    volumes:
      - nginx:/etc/nginx
    networks:
      - main-network

volumes:
  node-app:
    driver: local
  nginx:
    driver: local

networks:
  main-network:
    driver: bridge
