name: node-docker-pm2-ssl

services:
  # NODE
  node-app:
    image: sen00/node-docker-pm2-ssl:nodeapp
    container_name: node-app
    user: "node"
    volumes:
      - node-app:/home/node/node-app
    environment:
      - NODE_ENV=production
    networks:
      - main-network
  # NGINX
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: sen00/node-docker-pm2-ssl:nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-config:/etc/nginx/conf.d
    networks:
      - main-network
  # CERTBOT

volumes:
  node-app:
    driver: local
  nginx-config:
    driver: local

networks:
  main-network:
    driver: bridge
